name: File and Size Information
on:
  push:
    branches: [main] 
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate file and size information
        run: |
          total_files=$(git ls-files | wc -l)
          echo "Total files: $total_files"
          # Check if there's a parent commit
          if [ "$(git rev-list --max-count=2 HEAD)" != "$(git rev-parse HEAD)" ]; then
            changed_files=$(git diff HEAD^ HEAD --name-only | wc -l)
            echo "Changed files: $changed_files"
            changed_size=$(git diff HEAD^ HEAD --name-only | xargs du -sb | awk '{total += $1} END {print total}')
            echo "Changed size: $changed_size bytes"
          else
            echo "No parent commit found. Skipping changed files and size calculations."
            changed_files=0
            changed_size=0
          fi
          total_size=$(du -sb . | awk '{print $1}')
          echo "Total size: $total_size bytes"
          echo "Changed files: $changed_files"
          echo "Changed size: $changed_size bytes"
