name: File and Size Information

on:
  push:
    branches: [main]  # Replace with your desired branch

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate file and size information
        run: |

          total_files=$(git ls-files | wc -l)
          echo "Total files: $total_files"

          changed_files=$(git diff --name-only HEAD^ HEAD | wc -l)
          echo "Changed files: $changed_files"

          total_size=$(du -sb . | awk '{print $1}')
          echo "Total size: $total_size bytes"

          changed_size=$(git diff --name-only HEAD^ HEAD | xargs du -sb | awk '{total += $1} END {print total}')
          echo "Changed size: $changed_size bytes"
