name: Jekyll Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - '\_posts/**'
      - 'about.markdown'
      - 'index.markdown'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Jekyll environment (replace with your specific setup)
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1' # Replace with your Ruby version
      - run: bundle install

      # Build your Jekyll site
      - run: bundle exec jekyll build

      # Deploy to your desired location (replace with your deployment steps)
      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          provider: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: build

      # Add tags based on changed files
      - name: Add Tags
        run: |
          if [[ -n "$(git diff --name-only origin/main...HEAD _posts/*)" ]]; then
            git tag post
          fi
          if [[ -n "$(git diff --name-only origin/main...HEAD about.markdown)" ]]; then
            git tag about
          fi
          if [[ -n "$(git diff --name-only origin/main...HEAD index.markdown)" ]]; then
            git tag index
          fi
          git push origin --tags
