name: Jekyll Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - '\_posts/**'
      - 'about.markdown'
      - 'index.markdown'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # Add tags based on changed files/folder changes
      - name: Add Tags
        run: |
          if [[ -n "$(git diff --name-only origin/main...HEAD _posts/*)" ]]; then
            git tag post
          fi
          if [[ -n "$(git diff --name-only origin/main...HEAD about.markdown)" ]]; then
            git tag about
          fi
          if [[ -n "$(git diff --name-only origin/main...HEAD index.markdown)" ]]; then
            git tag index
          fi
          git push origin --tags
