name: Jekyll Auto Tagging

on:
  push:
    branches: [main] # Replace 'main' with your default branch
    paths:
      - '\_posts/**'
      - 'about.markdown'
      - 'index.markdown'

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for changes
        run: |
          if [ -n "$(git diff --name-only --diff-filter=AMRDTCW HEAD^ HEAD _post)" ]; then
            echo "post"
          elif [ -n "$(git diff --name-only --diff-filter=AMRDTCW HEAD^ HEAD about.markdown)" ]; then
            echo "about"
          elif [ -n "$(git diff --name-only --diff-filter=AMRDTCW HEAD^ HEAD index.markdown)" ]; then
            echo "index"
          fi
