name: Jekyll Auto Tagging

on:
  push:
    branches: [main] # Replace 'main' with your default branch
    paths:
      - '\_posts/**'
      - 'about.markdown'
      - 'index.markdown'

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine tag
        id: determine-tag
        run: |
          if [ "${{ github.event.changes._posts }}" ]; then
            echo "::set-output name=tag::post"
          elif [ "${{ github.event.changes.about.markdown }}" ]; then
            echo "::set-output name=tag::about"
          elif [ "${{ github.event.changes.index.markdown }}" ]; then
            echo "::set-output name=tag::index"
          fi
      - name: Create tag
        uses: actions/create-tag@v1
        with:
          tag_name: ${{ steps.determine-tag.outputs.tag }}
          tag_message: Automatically created tag

